export const PLACE_META = {
  上海: { altitude: 4, coord: [121.47, 31.23], scene: "city", summary: "出发与返程的锚点，负责整备、补给和节奏切换。", image: "/scenes/city-grid.svg" },
  昆明: { altitude: 1890, coord: [102.83, 24.88], scene: "city", summary: "进滇换乘节点，用来把航班和夜车衔接起来。", image: "/scenes/city-grid.svg" },
  丽江: { altitude: 2400, coord: [100.23, 26.88], scene: "city", summary: "高原适应起点，适合把车、人和行程节奏一起调顺。", image: "/scenes/city-grid.svg" },
  虎跳峡: { altitude: 1800, coord: [100.12, 27.39], scene: "desert", summary: "峡谷切面强烈，是正式进藏前很好的地形预热段。", image: "/scenes/canyon-vector.svg" },
  香格里拉: { altitude: 3200, coord: [99.7, 27.83], scene: "plateau", summary: "高海拔平台的前奏，进入长线推进模式。", image: "/scenes/plateau-vector.svg" },
  梅里雪山: { altitude: 3400, coord: [98.63, 28.42], scene: "ice", summary: "雪峰观景核心节点，视觉冲击很强。", image: "/scenes/ice-ridgeline.svg" },
  德钦: { altitude: 3400, coord: [98.91, 28.49], scene: "plateau", summary: "进入滇藏高线前的重要过夜点。", image: "/scenes/plateau-vector.svg" },
  芒康: { altitude: 3900, coord: [98.59, 29.68], scene: "plateau", summary: "路况与海拔同步抬升，正式进入硬核驾驶区。", image: "/scenes/plateau-vector.svg" },
  类乌齐: { altitude: 3900, coord: [96.61, 31.21], scene: "plateau", summary: "藏东高原腹地，典型的长距离推进日。", image: "/scenes/plateau-vector.svg" },
  孜珠寺: { altitude: 4800, coord: [95.65, 31.37], scene: "plateau", summary: "高位山寺，海拔和精神张力都很足。", image: "/scenes/plateau-vector.svg" },
  丁青: { altitude: 3870, coord: [95.62, 31.41], scene: "plateau", summary: "藏北推进中的节奏中继站。", image: "/scenes/plateau-vector.svg" },
  白嘎乡: { altitude: 4200, coord: [93.61, 31.82], scene: "plateau", summary: "靠近萨普神山的前置住宿点，适合把游玩日和长途推进日拆开。", image: "/scenes/plateau-vector.svg" },
  比如: { altitude: 3900, coord: [93.68, 31.48], scene: "plateau", summary: "前往萨普区域前的宿营与补给节点。", image: "/scenes/plateau-vector.svg" },
  比如人民政府: { altitude: 3900, coord: [93.69, 31.48], scene: "plateau", summary: "回到比如县城后的收束住宿点，方便次日直接西推。", image: "/scenes/plateau-vector.svg" },
  萨普神山: { altitude: 4300, coord: [93.9, 31.98], scene: "ice", summary: "徒步和雪山湖泊同框的高原爆点。", image: "/scenes/ice-ridgeline.svg" },
  圣象天门: { altitude: 4730, coord: [91.04, 31.8], scene: "lake", summary: "纳木错北岸的标志性机位，能把湖岸、石门和天光一起拉满。", image: "/scenes/lake-mirror.svg" },
  班戈: { altitude: 4700, coord: [90.01, 31.39], scene: "plateau", summary: "藏北高海拔推进阶段的耐力考验点。", image: "/scenes/plateau-vector.svg" },
  色林错: { altitude: 4550, coord: [88.71, 31.82], scene: "lake", summary: "大湖与荒原并置，适合切到开阔的风景节奏。", image: "/scenes/lake-mirror.svg" },
  日喀则: { altitude: 3840, coord: [88.88, 29.27], scene: "city", summary: "休整节点，车辆、体力和节奏都适合在这里归零再出发。", image: "/scenes/city-grid.svg" },
  珠峰大本营: { altitude: 5200, coord: [86.86, 28.14], scene: "ice", summary: "全程最具象征性的海拔极值点之一。", image: "/photos/everest-base-camp.jpg", creditKey: "everest-base-camp" },
  定日: { altitude: 4300, coord: [87.12, 28.66], scene: "plateau", summary: "珠峰段之后的回收与补能点。", image: "/scenes/plateau-vector.svg" },
  佩枯错: { altitude: 4600, coord: [85.58, 28.9], scene: "lake", summary: "风景极简，湖面和天际线非常适合静态镜头。", image: "/scenes/lake-mirror.svg" },
  帕羊: { altitude: 4700, coord: [84.3, 30.06], scene: "plateau", summary: "阿里线推进中的功能型节点。", image: "/scenes/plateau-vector.svg" },
  玛旁雍错: { altitude: 4588, coord: [81.28, 30.7], scene: "lake", summary: "神山圣湖体系里的视觉高潮之一。", image: "/photos/lake-manasarovar.jpg", creditKey: "lake-manasarovar" },
  冈仁波齐: { altitude: 4670, coord: [81.31, 31.07], scene: "plateau", summary: "整条路线的精神峰值点，叙事和氛围都应该在这里拉满。", image: "/photos/mount-kailash.jpg", creditKey: "mount-kailash" },
  塔尔钦: { altitude: 4575, coord: [81.17, 31.0], scene: "plateau", summary: "转山起止服务点，适合做补给和节奏重组。", image: "/scenes/plateau-vector.svg" },
  札达: { altitude: 3700, coord: [79.8, 31.47], scene: "desert", summary: "土林地貌强烈，带一点火星地表的气质。", image: "/scenes/canyon-vector.svg" },
  狮泉河: { altitude: 4300, coord: [80.1, 32.5], scene: "plateau", summary: "阿里腹地的核心补给点。", image: "/scenes/plateau-vector.svg" },
  班公湖: { altitude: 4250, coord: [79.7, 33.72], scene: "lake", summary: "边境湖面自带冷冽感，适合偏克制的大片构图。", image: "/scenes/lake-mirror.svg" },
  三十里营房: { altitude: 3700, coord: [79.1, 35.5], scene: "plateau", summary: "高强度长日程中的功能性落脚点。", image: "/scenes/plateau-vector.svg" },
  叶城: { altitude: 1400, coord: [77.42, 37.89], scene: "desert", summary: "从高海拔向南疆过渡的重要转折点。", image: "/scenes/canyon-vector.svg" },
  喀什: { altitude: 1300, coord: [75.99, 39.47], scene: "desert", summary: "南疆城市文明和长线驾驶节奏的汇合点。", image: "/scenes/canyon-vector.svg" },
  慕士塔格峰: { altitude: 3600, coord: [75.12, 38.28], scene: "ice", summary: "冰川、公路和高原天空很容易出大片。", image: "/photos/muztag-ata.jpg", creditKey: "muztag-ata" },
  塔县: { altitude: 3100, coord: [75.22, 37.77], scene: "plateau", summary: "帕米尔段的重要住宿与回旋点。", image: "/scenes/plateau-vector.svg" },
  盘龙古道: { altitude: 4200, coord: [75.54, 37.43], scene: "plateau", summary: "路线几何美学最强的驾驶亮点之一。", image: "/scenes/plateau-vector.svg" },
  温宿大峡谷: { altitude: 1400, coord: [79.2, 41.2], scene: "desert", summary: "地层切片感明显，适合粗粝、干燥的视觉风格。", image: "/photos/tianshan-canyon.jpg", creditKey: "tianshan-canyon" },
  库车: { altitude: 1100, coord: [82.96, 41.72], scene: "desert", summary: "独库公路南端的功能型节点。", image: "/scenes/canyon-vector.svg" },
  独库南段: { altitude: 2800, coord: [83.95, 42.6], scene: "plateau", summary: "弯道密度高，驾驶体验和景观变化同步拉升。", image: "/scenes/plateau-vector.svg" },
  乔尔玛: { altitude: 2500, coord: [83.56, 43.06], scene: "plateau", summary: "独库中段的重要分岔点，往唐布拉一拐，风景气质会立刻变柔和。", image: "/scenes/plateau-vector.svg" },
  唐布拉百里画廊: { altitude: 1500, coord: [83.21, 43.37], scene: "lake", summary: "草甸、河谷和林地连成一整段舒展画卷，是独库之后很好的修复段。", image: "/scenes/lake-mirror.svg" },
  新源: { altitude: 930, coord: [83.26, 43.43], scene: "city", summary: "从山路向伊犁河谷过渡的平衡点。", image: "/scenes/city-grid.svg" },
  库尔德宁: { altitude: 1500, coord: [82.64, 43.08], scene: "lake", summary: "草甸和林地带来一段柔和的中程修复感。", image: "/scenes/lake-mirror.svg" },
  特克斯: { altitude: 1200, coord: [81.84, 43.22], scene: "city", summary: "后半程的低压缓冲区。", image: "/scenes/city-grid.svg" },
  喀拉峻: { altitude: 2200, coord: [82.08, 43.01], scene: "lake", summary: "草原地形展开感很强，适合横向大视野画面。", image: "/scenes/lake-mirror.svg" },
  昭苏: { altitude: 1850, coord: [81.13, 43.16], scene: "lake", summary: "伊犁段机能感和松弛感切换的关键节点。", image: "/scenes/lake-mirror.svg" },
  夏塔: { altitude: 2100, coord: [80.82, 42.94], scene: "ice", summary: "雪峰、河谷和草地交叠，非常适合作为氛围切换点。", image: "/scenes/ice-ridgeline.svg" },
  伊宁: { altitude: 700, coord: [81.32, 43.92], scene: "city", summary: "西北绿洲城市节奏，画面会从硬核转向舒展。", image: "/scenes/city-grid.svg" },
  赛里木湖: { altitude: 2070, coord: [81.12, 44.6], scene: "lake", summary: "后段最强湖景节点，适合做压轴风景展示。", image: "/photos/sayram-lake.jpg", creditKey: "sayram-lake" },
  博乐: { altitude: 530, coord: [82.06, 44.91], scene: "city", summary: "赛里木湖之后的收束节点。", image: "/scenes/city-grid.svg" },
  独山子大峡谷: { altitude: 900, coord: [84.09, 44.33], scene: "desert", summary: "红褐色峡谷切面很利落，适合作为东返乌鲁木齐前的最后一记重景。", image: "/scenes/canyon-vector.svg" },
  天山天池: { altitude: 1910, coord: [88.12, 43.88], scene: "lake", summary: "返程前用一段高山湖景收尾，能把最后一天从赶路改成完整行程。", image: "/scenes/lake-mirror.svg" },
  乌鲁木齐: { altitude: 800, coord: [87.62, 43.82], scene: "city", summary: "西北段终点，也是返程转换站。", image: "/scenes/city-grid.svg" }
};

export const SCENE_META = {
  plateau: { label: "高原推进", gradient: "radial-gradient(circle at 18% 18%, rgba(255,224,163,0.14), transparent 30%), radial-gradient(circle at 82% 20%, rgba(99,163,117,0.12), transparent 28%), linear-gradient(135deg, #f5efe2 0%, #ddd3b6 48%, #b7a27a 100%)" },
  ice: { label: "雪线山脊", gradient: "radial-gradient(circle at top, rgba(255,255,255,0.22), transparent 24%), linear-gradient(135deg, #dfe9ef 0%, #b7c7d6 48%, #71879a 100%)" },
  desert: { label: "峡谷荒原", gradient: "radial-gradient(circle at 78% 18%, rgba(255,189,116,0.2), transparent 26%), linear-gradient(135deg, #f2dec3 0%, #d5b48c 46%, #9b6946 100%)" },
  lake: { label: "高海拔湖镜", gradient: "radial-gradient(circle at 20% 20%, rgba(208,241,241,0.22), transparent 26%), linear-gradient(135deg, #dbeceb 0%, #a9cbc7 46%, #5f8f96 100%)" },
  city: { label: "城市补能", gradient: "radial-gradient(circle at center, rgba(255,255,255,0.12), transparent 30%), linear-gradient(135deg, #ece6dc 0%, #cfc6b7 50%, #9f9485 100%)" }
};
